FROM php:alpine
WORKDIR /data

# Install PHP Dependencies
RUN apk --update --no-progress add freetype-dev libjpeg-turbo-dev libpng-dev
RUN docker-php-ext-configure gd \
  --enable-gd-native-ttf \
  --with-jpeg-dir=/usr/lib \
  --with-freetype-dir=/usr/include/freetype2
RUN docker-php-ext-install mcrypt pdo_mysql pdo_pgsql gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
